namespace: lvrfrc87
name: git_acp
version: 1.3.0
readme: README.md

authors:
    - Federico Olivieri <lvrfrc87@gmail.com>

description: Manage git add, git commit, git push and git config user on a local or remote git repository.
license:
    - GPL-3.0-only

repository: https://github.com/lvrfrc87/git-acp-ansible
documentation: https://github.com/lvrfrc87/git-acp-ansible/blob/master/README.md
homepage: https://github.com/lvrfrc87/git-acp-ansible
issues: https://github.com/lvrfrc87/git-acp-ansible/issues